### ISSUE TITLE
yt movie 

### ISSUE THREAD

**Issue by KornHolio216** [oliver-gomes/flutter-loginui#1]
set video to public mode(or if you know is private by your intention ignore)

**Comment by oliver-gomes** [comment]
Hey, Thanks for letting me know about the concern. I actually scheduled the video to be released by Tomorrow 2pm EST.  So comeback around then. Thanks 😃

**Comment by KornHolio216** [comment]
No problem thanks for informing me. 😃

niedz., 9 lut 2020 o 19:09 Oliver Gomes <notifications@github.com>
napisał(a):
