### ISSUE TITLE
Remove the debug banner

### ISSUE THREAD

**Issue by rsrinath14** [oliver-gomes/flutter-loginui#2]
Remove the debug banner by simply adding the following line in MaterialApp   

![debug banner example](https://user-images.githubusercontent.com/47494475/87989359-88464800-caff-11ea-900f-973e97f8dc9e.png)

return MaterialApp(
      debugShowCheckedModeBanner: false,

(ik its not that important, its just a suggestion :)  )

**Comment by oliver-gomes** [comment]
@srinath1412001 yeah not important at all and I know but thanks for the suggestion, will do
